### ISSUE TITLE
Blocking 10.10.34.35 problem

### ISSUE THREAD

**Issue by H-Ir** [SamadiPour/iran-hosted-domains#55]
You have added 10.10.34.35 and 10.10.34.36 ips to the blocked **_domains_** section but it is incorrect specially for qv2ray app. Please add it to the blocked **_IPs_** section. Tnx

**Comment by SamadiPour** [comment]
Fixed by 5bd2f69cc7457bac299551451cdaeb098b1600b6

**Comment by H-Ir** [comment]
@SamadiPour 
Tnx but you didn't add these ips to the _**Blocked IPs**_ section! I Mean:

![Capture](https://user-images.githubusercontent.com/15199851/206533329-b82d5a7b-0670-449f-b399-f470235d44eb.JPG)

**Comment by H-Ir** [comment]
Yes, there is no `10.10.34.35` in the new commit but I just said to move `10.10.34.35` and `10.10.34.36` from `blocked domain` section to the `blocked IP` section, not completely remove them.

**Comment by SamadiPour** [comment]
To be fair, `10.10.34.35/36` doesn't count as an AD domain. It's just a stupid site that exists, and you are using VPN so you probably don't get redirected to it.
For me, it was important to remove it because it was an IP in the Domain list and some apps might not work properly with this list just because of that.
