### ISSUE TITLE
Clash Config

### ISSUE THREAD

**Issue by AmiiirCom** [SamadiPour/iran-hosted-domains#6]
please add clash config

**Comment by SamadiPour** [comment]
Try using Dat file.

**Comment by AmiiirCom** [comment]
How? Please explain to me.

**Comment by Tirbod** [comment]
Open your clash profile .yml file with any text editor and copy either of below files' content(each correspondent to original [ir_domains and other_domains files](https://github.com/SamadiPour/iran-hosted-domains/releases/tag/202108130905)) and add them below `rules:` in .yml file(to bypass included domains)
you can also add`  - GEOIP,IR,✅ Direct` to bypass Iran based domains that included in [maxmind-geoip](https://github.com/Dreamacro/maxmind-geoip)
and alternatively you can add`  - DOMAIN-SUFFIX,.ir,✅ Direct` that bypass all .ir domains instead of using ir_domains
[](url)
[other_domains_clash.txt](https://github.com/SamadiPour/iran-hosted-domains/files/7008718/other_domains_clash.txt)
[ir_domains_clash.txt](https://github.com/SamadiPour/iran-hosted-domains/files/7008721/ir_domains_clash.txt)

**Comment by AmiiirCom** [comment]
Ok, Thx ❤️

**Comment by Tirbod** [comment]
There is another and perhaps better way for doing this with [Mixin](https://docs.cfw.lbyczf.com/contents/mixin.html#%E7%89%88%E6%9C%AC%E8%A6%81%E6%B1%82)(its not available in mobile client but both [Clash for Windows](https://github.com/Fndroid/clash_for_windows_pkg) and [Clash .NET](https://github.com/ClashDotNetFramework/ClashDotNetFramework/tree/main) have this feature) 
With Mixin you can introduce any change to config and it will be apply to any profile that you are using and override it(without changing anything in profile) as long as you have Mixin turned on.
so in this case locate Mixin profile in settings and open YAML file and below `mixin:` write `  rules:` and add **all of your rules** below it (those two spaces before`  rules: ` are essential)
Note: with doing this all of your profile's rules will be ignored and rules that you introduced in Mixin will be used (as long as you have Mixin turned on)
